<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Branding">
    <RDOCBaseName>ripperk</RDOCBaseName>
    <RDOCBaseNameUpper>RIPPERK</RDOCBaseNameUpper>
    <RDOCProductName>ripperK</RDOCProductName>
    <RDOCCompatBaseName>ripperk</RDOCCompatBaseName>
    <RDOCCompatBaseNameUpper>RIPPERK</RDOCCompatBaseNameUpper>
    <RDOCCompatAppHeaderName>$(RDOCCompatBaseName)_app.h</RDOCCompatAppHeaderName>
    <RDOCCompatReplayHeaderName>$(RDOCCompatBaseName)_replay.h</RDOCCompatReplayHeaderName>
    <RDOCCompatGetAPIName>$(RDOCCompatBaseNameUpper)_GetAPI</RDOCCompatGetAPIName>
    <RDOCCompatReplayMarkerName>$(RDOCCompatBaseName)__replay__marker</RDOCCompatReplayMarkerName>
    <RDOCCoreTargetName>$(RDOCBaseName)</RDOCCoreTargetName>
    <RDOCCmdTargetName>ripperkcmd</RDOCCmdTargetName>
    <RDOCCmdDisplayName>ripperKCmd</RDOCCmdDisplayName>
    <RDOCPyCoreModuleTargetName>ripperk</RDOCPyCoreModuleTargetName>
    <RDOCPyGuiModuleTargetName>qripperk</RDOCPyGuiModuleTargetName>
    <RDOCGuiTargetName>qripperk</RDOCGuiTargetName>
    <RDOCGuiStubTargetName>ripperkui</RDOCGuiStubTargetName>
    <RDOCShimBaseTargetName>ripperkshim</RDOCShimBaseTargetName>
    <RDOCShim32TargetName>$(RDOCShimBaseTargetName)32</RDOCShim32TargetName>
    <RDOCShim64TargetName>$(RDOCShimBaseTargetName)64</RDOCShim64TargetName>
    <RDOCVulkanLayerName>VK_LAYER_$(RDOCBaseNameUpper)_Capture</RDOCVulkanLayerName>
    <RDOCVulkanEnableVar>ENABLE_VULKAN_$(RDOCBaseNameUpper)_CAPTURE</RDOCVulkanEnableVar>
    <RDOCVulkanLayerDescription>Debugging capture layer for $(RDOCProductName)</RDOCVulkanLayerDescription>
    <RDOCVulkanGetInstanceProcAddr>$(RDOCVulkanLayerName)GetInstanceProcAddr</RDOCVulkanGetInstanceProcAddr>
    <RDOCVulkanGetDeviceProcAddr>$(RDOCVulkanLayerName)GetDeviceProcAddr</RDOCVulkanGetDeviceProcAddr>
    <RDOCVulkanNegotiateLoaderLayerInterfaceVersion>$(RDOCVulkanLayerName)NegotiateLoaderLayerInterfaceVersion</RDOCVulkanNegotiateLoaderLayerInterfaceVersion>
    <RDOCVulkanEnumerateInstanceExtensionProperties>$(RDOCVulkanLayerName)EnumerateInstanceExtensionProperties</RDOCVulkanEnumerateInstanceExtensionProperties>
  </PropertyGroup>
</Project>
