set(RDOC_BASE_NAME "ripperk")
if(INTERNAL_SELF_CAPTURE)
    set(RDOC_BASE_NAME "rdocself")
    add_definitions(-DRDOC_SELFCAPTURE_LIMITEDAPI=1)
endif()

set(RDOC_PRODUCT_NAME "ripperK")
set(RDOC_CMD_NAME "ripperkcmd")
set(RDOC_CMD_DISPLAY_NAME "ripperKCmd")
set(RDOC_COMPAT_BASE_NAME "ripperk")
set(RDOC_COMPAT_BASE_NAME_UPPER "RIPPERK")
set(RDOC_COMPAT_APP_HEADER_NAME "ripperk_app.h")
set(RDOC_COMPAT_REPLAY_HEADER_NAME "ripperk_replay.h")
set(RDOC_COMPAT_GETAPI_NAME "RIPPERK_GetAPI")
set(RDOC_COMPAT_REPLAY_MARKER_NAME "ripperk__replay__marker")
set(RDOC_CORE_OUTPUT_NAME "${RDOC_BASE_NAME}")
set(RDOC_GUI_TARGET_NAME "qripperk")
set(RDOC_CMD_OUTPUT_NAME "ripperkcmd")
set(RDOC_PY_CORE_MODULE_NAME "ripperk")
set(RDOC_PY_GUI_MODULE_NAME "qripperk")
set(RDOC_GUI_BUNDLE_ICON_NAME "ripperK.icns")
set(RDOC_CORE_MAC_DYLIB_NAME "libripperk.dylib")
set(RDOC_ANDROID_OUTPUT_NAME "VkLayer_GLES_ripperK")

if(INTERNAL_SELF_CAPTURE)
    set(RDOC_CMD_OUTPUT_NAME "rdocselfcmd")
endif()

set(RDOC_ANDROID_PACKAGE_BASE "org.ripperk.ripperkcmd")
set(RDOC_ANDROID_ACTIVITY_LABEL "ripperK")
set(RDOC_ANDROID_APPLICATION_LABEL "ripperKCmd")
set(RDOC_ANDROID_INTENT_EXTRA_KEY "ripperkcmd")
set(RDOC_ANDROID_APK_BASENAME "ripperKCmd")
set(RDOC_VULKAN_LAYER_DESCRIPTION "Debugging capture layer for ripperK")
set(RDOC_POSIX_SHARE_DIR "ripperk")
set(RDOC_PYLIBS_SHARE_SUBDIR "share/ripperk/pylibs")
set(RDOC_PLUGINS_SHARE_SUBDIR "share/ripperk/plugins")
set(RDOC_ANDROID_PLUGINS_SHARE_SUBDIR "share/ripperk/plugins/android")
set(RDOC_MIME_TYPE "application/x-ripperk-capture")
set(RDOC_MIME_ICON_NAME "application-x-ripperk-capture")
set(RDOC_DESKTOP_FILE_NAME "ripperk.desktop")
set(RDOC_THUMBNAILER_FILE_NAME "ripperk.thumbnailer")
set(RDOC_CAPTURE_XML_FILE_NAME "ripperk-capture.xml")
set(RDOC_MENU_FILE_NAME "ripperk")
set(RDOC_PIXMAP_ICON_16_FILE_NAME "ripperk-icon-16x16.xpm")
set(RDOC_PIXMAP_ICON_32_FILE_NAME "ripperk-icon-32x32.xpm")
set(RDOC_CAPTURE_MAGIC "RIPK")

string(TOUPPER ${RDOC_BASE_NAME} RDOC_BASE_NAME_UPPER)
add_definitions(-DRDOC_BASE_NAME=${RDOC_BASE_NAME})
add_definitions(-DRDOC_BASE_NAME_UPPER=${RDOC_BASE_NAME_UPPER})
