<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Branding">
    <RDOCBaseName>ripperk</RDOCBaseName>
    <RDOCBaseNameUpper>RIPPERK</RDOCBaseNameUpper>
    <RDOCProductName>ripperK</RDOCProductName>
    <RDOCCompatBaseName>ripperk</RDOCCompatBaseName>
    <RDOCCompatBaseNameUpper>RIPPERK</RDOCCompatBaseNameUpper>
    <RDOCCompatAppHeaderName>ripperk_app.h</RDOCCompatAppHeaderName>
    <RDOCCompatReplayHeaderName>ripperk_replay.h</RDOCCompatReplayHeaderName>
    <RDOCCompatGetAPIName>RIPPERK_GetAPI</RDOCCompatGetAPIName>
    <RDOCCompatReplayMarkerName>ripperk__replay__marker</RDOCCompatReplayMarkerName>
    <RDOCCoreTargetName>$(RDOCBaseName)</RDOCCoreTargetName>
    <RDOCCmdTargetName>ripperkcmd</RDOCCmdTargetName>
    <RDOCCmdDisplayName>ripperKCmd</RDOCCmdDisplayName>
    <RDOCPyCoreModuleTargetName>ripperk</RDOCPyCoreModuleTargetName>
    <RDOCPyGuiModuleTargetName>qripperk</RDOCPyGuiModuleTargetName>
    <RDOCGuiTargetName>qripperk</RDOCGuiTargetName>
    <RDOCGuiStubTargetName>ripperkui</RDOCGuiStubTargetName>
    <RDOCShimBaseTargetName>ripperkshim</RDOCShimBaseTargetName>
    <RDOCShim32TargetName>$(RDOCShimBaseTargetName)32</RDOCShim32TargetName>
    <RDOCShim64TargetName>$(RDOCShimBaseTargetName)64</RDOCShim64TargetName>
    <RDOCVulkanLayerName>VK_LAYER_RIPPERK_Capture</RDOCVulkanLayerName>
    <RDOCVulkanEnableVar>ENABLE_VULKAN_RIPPERK_CAPTURE</RDOCVulkanEnableVar>
    <RDOCVulkanLayerDescription>Debugging capture layer for ripperK</RDOCVulkanLayerDescription>
    <RDOCVulkanGetInstanceProcAddr>$(RDOCVulkanLayerName)GetInstanceProcAddr</RDOCVulkanGetInstanceProcAddr>
    <RDOCVulkanGetDeviceProcAddr>$(RDOCVulkanLayerName)GetDeviceProcAddr</RDOCVulkanGetDeviceProcAddr>
    <RDOCVulkanNegotiateLoaderLayerInterfaceVersion>$(RDOCVulkanLayerName)NegotiateLoaderLayerInterfaceVersion</RDOCVulkanNegotiateLoaderLayerInterfaceVersion>
    <RDOCVulkanEnumerateInstanceExtensionProperties>$(RDOCVulkanLayerName)EnumerateInstanceExtensionProperties</RDOCVulkanEnumerateInstanceExtensionProperties>
  </PropertyGroup>
</Project>
