from pathlib import Path
import sys

import rdoc_brand as brand

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = {
    'util/brand_templates/brand_config.h.in': 'renderdoc/common/brand_config.h',
    'util/brand_templates/Branding.props.in': 'util/Branding.props',
    'util/brand_templates/Branding.wxi.in': 'util/installer/Branding.wxi',
    'util/brand_templates/Branding.cmake.in': 'util/Branding.cmake',
}


def _bool(value: bool) -> str:
    return '1' if value else '0'


REPLACEMENTS = {
    '@RDOC_PRODUCT_NAME@': brand.PRODUCT_NAME,
    '@RDOC_REPLAY_BASE_NAME@': brand.REPLAY_BASE_NAME,
    '@RDOC_CAPTURE_APP_BASE_NAME@': brand.CAPTURE_APP_BASE_NAME,
    '@RDOC_BASE_NAME@': brand.BASE_NAME,
    '@RDOC_BASE_NAME_UPPER@': brand.BASE_NAME_UPPER,
    '@RDOC_BASE_NAME_UPPER_TOKEN@': brand.BASE_NAME_UPPER,
    '@RDOC_UI_NAME@': brand.UI_NAME,
    '@RDOC_UI_DISPLAY_NAME@': brand.UI_DISPLAY_NAME,
    '@RDOC_UI_EXECUTABLE@': brand.UI_EXECUTABLE,
    '@RDOC_UI_INTERNAL_NAME@': brand.UI_INTERNAL_NAME,
    '@RDOC_UI_STUB_NAME@': brand.UI_STUB_NAME,
    '@RDOC_UI_STUB_EXECUTABLE@': brand.UI_STUB_EXECUTABLE,
    '@RDOC_CMD_NAME@': brand.CMD_NAME,
    '@RDOC_CMD_DISPLAY_NAME@': brand.CMD_DISPLAY_NAME,
    '@RDOC_CMD_EXECUTABLE@': brand.CMD_EXECUTABLE,
    '@RDOC_CMD_INTERNAL_NAME@': brand.CMD_INTERNAL_NAME,
    '@RDOC_CORE_DLL_NAME@': brand.CORE_DLL_NAME,
    '@RDOC_CORE_INTERNAL_NAME@': brand.CORE_INTERNAL_NAME,
    '@RDOC_CORE_JSON_NAME@': brand.CORE_JSON_NAME,
    '@RDOC_SHIM_NAME@': brand.SHIM_NAME,
    '@RDOC_SHIM_DLL_64@': brand.SHIM_DLL_64,
    '@RDOC_SHIM_DLL_32@': brand.SHIM_DLL_32,
    '@RDOC_GLOBAL_HOOK_DATA_NAME_64@': brand.GLOBAL_HOOK_DATA_NAME_64,
    '@RDOC_GLOBAL_HOOK_DATA_NAME_32@': brand.GLOBAL_HOOK_DATA_NAME_32,
    '@RDOC_GLOBAL_HOOK_RESTORE_FILENAME@': brand.GLOBAL_HOOK_RESTORE_FILENAME,
    '@RDOC_TEMP_SUBFOLDER@': brand.TEMP_SUBFOLDER,
    '@RDOC_APPDATA_SUBFOLDER@': brand.APPDATA_SUBFOLDER,
    '@RDOC_CAPTURE_PROGID@': brand.CAPTURE_PROGID,
    '@RDOC_SETTINGS_PROGID@': brand.SETTINGS_PROGID,
    '@RDOC_CAPTURE_EXTENSION@': brand.CAPTURE_EXTENSION,
    '@RDOC_CAPTURE_FILETYPE@': brand.CAPTURE_FILETYPE,
    '@RDOC_SETTINGS_EXTENSION@': brand.SETTINGS_EXTENSION,
    '@RDOC_SETTINGS_FILETYPE@': brand.SETTINGS_FILETYPE,
    '@RDOC_CAPTURE_MAGIC@': brand.CAPTURE_MAGIC,
    '@RDOC_CAPTURE_MAGIC_CHAR_0@': brand.CAPTURE_MAGIC[0],
    '@RDOC_CAPTURE_MAGIC_CHAR_1@': brand.CAPTURE_MAGIC[1],
    '@RDOC_CAPTURE_MAGIC_CHAR_2@': brand.CAPTURE_MAGIC[2],
    '@RDOC_CAPTURE_MAGIC_CHAR_3@': brand.CAPTURE_MAGIC[3],
    '@RDOC_LEGACY_CAPTURE_MAGIC@': brand.LEGACY_CAPTURE_MAGIC,
    '@RDOC_LEGACY_CAPTURE_MAGIC_CHAR_0@': brand.LEGACY_CAPTURE_MAGIC[0],
    '@RDOC_LEGACY_CAPTURE_MAGIC_CHAR_1@': brand.LEGACY_CAPTURE_MAGIC[1],
    '@RDOC_LEGACY_CAPTURE_MAGIC_CHAR_2@': brand.LEGACY_CAPTURE_MAGIC[2],
    '@RDOC_LEGACY_CAPTURE_MAGIC_CHAR_3@': brand.LEGACY_CAPTURE_MAGIC[3],
    '@RDOC_READ_LEGACY_CAPTURE_MAGIC@': _bool(brand.READ_LEGACY_CAPTURE_MAGIC),
    '@RDOC_CRASH_EVENT_NAME@': brand.CRASH_EVENT_NAME,
    '@RDOC_BREAKPAD_PIPE_PREFIX@': brand.BREAKPAD_PIPE_PREFIX,
    '@RDOC_UPDATE_TEMPDIR@': brand.UPDATE_TEMPDIR,
    '@RDOC_MANUFACTURER_NAME@': brand.MANUFACTURER_NAME,
    '@RDOC_WEBSITE_URL@': brand.WEBSITE_URL,
    '@RDOC_DOCUMENTATION_TITLE@': brand.DOCUMENTATION_TITLE,
    '@RDOC_DOCUMENTATION_HTML_TITLE@': brand.DOCUMENTATION_HTML_TITLE,
    '@RDOC_DOCUMENTATION_COLLECTION_NAME@': brand.DOCUMENTATION_COLLECTION_NAME,
    '@RDOC_DOCUMENTATION_BASENAME@': brand.DOCUMENTATION_BASENAME,
    '@RDOC_DOCUMENTATION_FILE@': brand.DOCUMENTATION_FILE,
    '@RDOC_DOCUMENTATION_URL@': brand.DOCUMENTATION_URL,
    '@RDOC_PYTHON_API_URL@': brand.PYTHON_API_URL,
    '@RDOC_IN_APPLICATION_API_URL@': brand.IN_APPLICATION_API_URL,
    '@RDOC_BUILDS_URL@': brand.BUILDS_URL,
    '@RDOC_UPDATE_URL_TEMPLATE@': brand.UPDATE_URL_PATTERN.replace('{bitness}', '%1').replace('{version}', '%2'),
    '@RDOC_TIPS_URL_TEMPLATE@': brand.TIPS_URL_PATTERN.replace('{index}', '%1'),
    '@RDOC_SUPPORT_EMAIL@': brand.SUPPORT_EMAIL,
    '@RDOC_SOURCE_URL@': brand.SOURCE_URL,
    '@RDOC_ISSUES_URL@': brand.ISSUES_URL,
    '@RDOC_CONTRIB_URL@': brand.CONTRIB_URL,
    '@RDOC_PY_CORE_MODULE_NAME@': brand.PY_CORE_MODULE_NAME,
    '@RDOC_PY_GUI_MODULE_NAME@': brand.PY_GUI_MODULE_NAME,
    '@RDOC_KEEP_LEGACY_PYTHON_ALIASES@': _bool(brand.KEEP_LEGACY_PYTHON_ALIASES),
    '@RDOC_KEEP_LEGACY_ABI@': _bool(brand.KEEP_LEGACY_ABI),
    '@RDOC_KEEP_LEGACY_POSIX_ENVS@': _bool(brand.KEEP_LEGACY_POSIX_ENVS),
    '@RDOC_LINUX_CORE_LIBRARY@': brand.LINUX_CORE_LIBRARY,
    '@RDOC_APPLE_CORE_LIBRARY@': brand.APPLE_CORE_LIBRARY,
    '@RDOC_ANDROID_CAPTURE_LIBRARY@': brand.ANDROID_CAPTURE_LIBRARY,
    '@RDOC_VULKAN_LAYER_NAME@': brand.VULKAN_LAYER_NAME,
    '@RDOC_VULKAN_CAPTURE_VAR@': brand.VULKAN_CAPTURE_VAR,
    '@RDOC_VULKAN_LAYER_DESCRIPTION@': brand.VULKAN_LAYER_DESCRIPTION,
    '@RDOC_VULKAN_FORCED_INSTANCE_NAME@': brand.VULKAN_FORCED_INSTANCE_NAME,
    '@RDOC_VULKAN_TOOL_NAME@': brand.VULKAN_TOOL_NAME,
    '@RDOC_VULKAN_TOOL_DESCRIPTION@': brand.VULKAN_TOOL_DESCRIPTION,
    '@RDOC_VULKAN_CAPTURE_APP_NAME@': brand.VULKAN_CAPTURE_APP_NAME,
    '@RDOC_VULKAN_ENGINE_NAME@': brand.VULKAN_ENGINE_NAME,
    '@RDOC_ANDROID_LIBRARY@': brand.ANDROID_LIBRARY,
    '@RDOC_ANDROID_PACKAGE_BASE@': brand.CMD_ANDROID_PACKAGE_BASE,
    '@RDOC_CMD_ANDROID_EXTRA_KEY@': brand.CMD_ANDROID_EXTRA_KEY,
    '@RDOC_BUGREPORT_URL@': brand.BUGREPORT_URL,
    '@RDOC_ANALYTICS_URL@': brand.ANALYTICS_URL,
    '@RDOC_SECTION_INTERNAL_PREFIX@': brand.SECTION_INTERNAL_PREFIX,
    '@RDOC_SECTION_UI_PREFIX@': brand.SECTION_UI_PREFIX,
    '@RDOC_SECTION_FRAMECAPTURE@': brand.SECTION_FRAMECAPTURE,
    '@RDOC_SECTION_RESOLVEDB@': brand.SECTION_RESOLVEDB,
    '@RDOC_SECTION_BOOKMARKS@': brand.SECTION_BOOKMARKS,
    '@RDOC_SECTION_NOTES@': brand.SECTION_NOTES,
    '@RDOC_SECTION_RESRENAMES@': brand.SECTION_RESRENAMES,
    '@RDOC_SECTION_EXTHUMB@': brand.SECTION_EXTHUMB,
    '@RDOC_SECTION_LOGFILE@': brand.SECTION_LOGFILE,
    '@RDOC_SECTION_EDITS@': brand.SECTION_EDITS,
    '@RDOC_SECTION_D3D12CORE@': brand.SECTION_D3D12CORE,
    '@RDOC_SECTION_D3D12SDKLAYERS@': brand.SECTION_D3D12SDKLAYERS,
    '@RDOC_SECTION_EMBEDDED_EXTERNALS@': brand.SECTION_EMBEDDED_EXTERNALS,
    '@RDOC_ENV_ORIGLIBPATH@': brand.ENV_ORIGLIBPATH,
    '@RDOC_ENV_ORIGPRELOAD@': brand.ENV_ORIGPRELOAD,
    '@RDOC_ENV_CAPFILE@': brand.ENV_CAPFILE,
    '@RDOC_ENV_CAPOPTS@': brand.ENV_CAPOPTS,
    '@RDOC_ENV_DEBUG_LOG_FILE@': brand.ENV_DEBUG_LOG_FILE,
    '@RDOC_ENV_TEMP@': brand.ENV_TEMP,
    '@RDOC_ENV_HOOK_EGL@': brand.ENV_HOOK_EGL,
    '@RDOC_ENV_DEMOS_DATA@': brand.ENV_DEMOS_DATA,
    '@RDOC_POSIX_CONFIG_DIR@': brand.POSIX_CONFIG_DIR,
    '@RDOC_POSIX_SHARE_DIR@': brand.POSIX_SHARE_DIR,
    '@RDOC_SETTINGS_FILENAME@': brand.SETTINGS_FILENAME,
    '@RDOC_REMOTE_SERVER_CONFIG_FILENAME@': brand.REMOTE_SERVER_CONFIG_FILENAME,
    '@RDOC_PLUGINS_SHARE_SUBDIR@': brand.PLUGINS_SHARE_SUBDIR,
    '@RDOC_ANDROID_PLUGINS_SHARE_SUBDIR@': brand.ANDROID_PLUGINS_SHARE_SUBDIR,
    '@RDOC_PYLIBS_SHARE_SUBDIR@': brand.PYLIBS_SHARE_SUBDIR,
    '@RDOC_MIME_TYPE@': brand.MIME_TYPE,
    '@RDOC_MIME_ICON_NAME@': brand.MIME_ICON_NAME,
    '@RDOC_DESKTOP_FILENAME@': brand.DESKTOP_FILENAME,
    '@RDOC_THUMBNAILER_FILENAME@': brand.THUMBNAILER_FILENAME,
    '@RDOC_CAPTURE_XML_FILENAME@': brand.CAPTURE_XML_FILENAME,
    '@RDOC_MENU_FILENAME@': brand.MENU_FILENAME,
    '@RDOC_PIXMAP_ICON_16_FILENAME@': brand.PIXMAP_ICON_16_FILENAME,
    '@RDOC_PIXMAP_ICON_32_FILENAME@': brand.PIXMAP_ICON_32_FILENAME,
    '@RDOC_THUMBNAIL_HANDLER_NAME@': brand.THUMBNAIL_HANDLER_NAME,
    '@RDOC_FILE_ASSOCIATIONS_DESCRIPTION@': brand.FILE_ASSOCIATIONS_DESCRIPTION,
    '@RDOC_GUI_BUNDLE_ICON_NAME@': brand.GUI_BUNDLE_ICON_NAME,
    '@RDOC_CORE_MAC_DYLIB_NAME@': brand.CORE_MAC_DYLIB_NAME,
    '@RDOC_ANDROID_OUTPUT_NAME@': brand.ANDROID_OUTPUT_NAME,
    '@RDOC_ANDROID_ACTIVITY_LABEL@': brand.ANDROID_ACTIVITY_LABEL,
    '@RDOC_ANDROID_APPLICATION_LABEL@': brand.ANDROID_APPLICATION_LABEL,
    '@RDOC_ANDROID_APK_BASENAME@': brand.ANDROID_APK_BASENAME,
    '@RDOC_ANDROID_PROPERTY_PREFIX@': brand.ANDROID_PROPERTY_PREFIX,
    '@RDOC_ANDROID_AUTOGRANT_PERMISSIONS_PROPERTY@': brand.ANDROID_AUTOGRANT_PERMISSIONS_PROPERTY,
    '@RDOC_ANDROID_IGNORE_LAYERS_PROPERTY@': brand.ANDROID_IGNORE_LAYERS_PROPERTY,
    '@RDOC_ANDROID_CAPTURE_OPTIONS_PROPERTY@': brand.ANDROID_CAPTURE_OPTIONS_PROPERTY,
    '@RDOC_ANDROID_SOCKET_PREFIX@': brand.ANDROID_SOCKET_PREFIX,
    '@RDOC_COMPAT_BASE_NAME@': brand.COMPAT_BASE_NAME,
    '@RDOC_COMPAT_BASE_NAME_UPPER@': brand.COMPAT_BASE_NAME_UPPER,
    '@RDOC_COMPAT_APP_HEADER_NAME@': brand.COMPAT_APP_HEADER_NAME,
    '@RDOC_COMPAT_REPLAY_HEADER_NAME@': brand.COMPAT_REPLAY_HEADER_NAME,
    '@RDOC_COMPAT_GETAPI_NAME@': brand.COMPAT_GETAPI_NAME,
    '@RDOC_COMPAT_REPLAY_MARKER_NAME@': brand.COMPAT_REPLAY_MARKER_NAME,
}


def render_template(path: Path) -> str:
    text = path.read_text()
    for key, value in REPLACEMENTS.items():
        text = text.replace(key, value)
    return text


def main() -> int:
    check = '--check' in sys.argv[1:]
    dirty = []

    for src_rel, dst_rel in TEMPLATES.items():
        src = ROOT / src_rel
        dst = ROOT / dst_rel
        rendered = render_template(src)

        if check:
            if not dst.exists() or dst.read_text() != rendered:
                dirty.append(dst_rel)
            continue

        dst.write_text(rendered)

    if check and dirty:
        for path in dirty:
            print(path)
        return 1

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
