import os
from urllib.parse import quote


def _getenv(name: str, default: str) -> str:
    return os.environ.get(name, default)


def _getbool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def _mailto_url(subject: str) -> str:
    return f"mailto:{SUPPORT_EMAIL}?subject={quote(subject)}"


def _fourcc(name: str, default: str) -> str:
    value = _getenv(name, default)
    if len(value) != 4:
        raise ValueError(f"{name} must be exactly 4 characters, got {value!r}")
    return value


PRODUCT_NAME = _getenv('RDOC_PRODUCT_NAME', 'ripperK')
BASE_NAME = _getenv('RDOC_BASE_NAME', 'ripperk')
BASE_NAME_UPPER = _getenv('RDOC_BASE_NAME_UPPER', BASE_NAME.upper())
REPLAY_BASE_NAME = _getenv('RDOC_REPLAY_BASE_NAME', PRODUCT_NAME)
CAPTURE_APP_BASE_NAME = _getenv('RDOC_CAPTURE_APP_BASE_NAME', PRODUCT_NAME + '_app')

COMPAT_BASE_NAME = _getenv('RDOC_COMPAT_BASE_NAME', BASE_NAME)
COMPAT_BASE_NAME_UPPER = _getenv('RDOC_COMPAT_BASE_NAME_UPPER', COMPAT_BASE_NAME.upper())
COMPAT_APP_HEADER_NAME = _getenv('RDOC_COMPAT_APP_HEADER_NAME', COMPAT_BASE_NAME + '_app.h')
COMPAT_REPLAY_HEADER_NAME = _getenv(
    'RDOC_COMPAT_REPLAY_HEADER_NAME',
    COMPAT_BASE_NAME + '_replay.h',
)
COMPAT_GETAPI_NAME = _getenv('RDOC_COMPAT_GETAPI_NAME', COMPAT_BASE_NAME_UPPER + '_GetAPI')
COMPAT_REPLAY_MARKER_NAME = _getenv(
    'RDOC_COMPAT_REPLAY_MARKER_NAME',
    COMPAT_BASE_NAME + '__replay__marker',
)

MANUFACTURER_NAME = _getenv('RDOC_MANUFACTURER_NAME', 'Baldur Karlsson')

UI_NAME = _getenv('RDOC_UI_NAME', 'qripperk')
UI_DISPLAY_NAME = _getenv('RDOC_UI_DISPLAY_NAME', 'QripperK')
UI_EXECUTABLE = _getenv('RDOC_UI_EXECUTABLE', UI_NAME + '.exe')
UI_INTERNAL_NAME = _getenv('RDOC_UI_INTERNAL_NAME', UI_NAME)
UI_STUB_NAME = _getenv('RDOC_UI_STUB_NAME', 'ripperkui')
UI_STUB_EXECUTABLE = _getenv('RDOC_UI_STUB_EXECUTABLE', UI_STUB_NAME + '.exe')
CMD_NAME = _getenv('RDOC_CMD_NAME', 'ripperkcmd')
CMD_DISPLAY_NAME = _getenv('RDOC_CMD_DISPLAY_NAME', 'ripperKCmd')
CMD_EXECUTABLE = _getenv('RDOC_CMD_EXECUTABLE', CMD_NAME + '.exe')
CMD_INTERNAL_NAME = _getenv('RDOC_CMD_INTERNAL_NAME', CMD_EXECUTABLE)
CORE_DLL_NAME = _getenv('RDOC_CORE_DLL_NAME', BASE_NAME + '.dll')
CORE_INTERNAL_NAME = _getenv('RDOC_CORE_INTERNAL_NAME', BASE_NAME)
CORE_JSON_NAME = _getenv('RDOC_CORE_JSON_NAME', BASE_NAME + '.json')
SHIM_NAME = _getenv('RDOC_SHIM_NAME', 'ripperkshim')
SHIM_DLL_64 = _getenv('RDOC_SHIM_DLL_64', SHIM_NAME + '64.dll')
SHIM_DLL_32 = _getenv('RDOC_SHIM_DLL_32', SHIM_NAME + '32.dll')
GUI_BUNDLE_ICON_NAME = _getenv('RDOC_GUI_BUNDLE_ICON_NAME', PRODUCT_NAME + '.icns')
CORE_MAC_DYLIB_NAME = _getenv('RDOC_CORE_MAC_DYLIB_NAME', 'lib' + BASE_NAME + '.dylib')
ANDROID_OUTPUT_NAME = _getenv('RDOC_ANDROID_OUTPUT_NAME', 'VkLayer_GLES_' + PRODUCT_NAME)

UPGRADE_COMMAND = _getenv('RDOC_UPGRADE_COMMAND', 'upgrade')
CRASH_HANDLE_COMMAND = _getenv('RDOC_CRASH_HANDLE_COMMAND', 'crashhandle')
GLOBAL_HOOK_COMMAND = _getenv('RDOC_GLOBAL_HOOK_COMMAND', 'globalhook')

UPDATE_FAILED_OPTION = _getenv('RDOC_UPDATE_FAILED_OPTION', 'updatefailed')
UPDATE_DONE_ADMIN_OPTION = _getenv('RDOC_UPDATE_DONE_ADMIN_OPTION', 'updatedone_admin')
UPDATE_DONE_OPTION = _getenv('RDOC_UPDATE_DONE_OPTION', 'updatedone')
CRASH_OPTION = _getenv('RDOC_CRASH_OPTION', 'crash')

GLOBAL_HOOK_DATA_NAME_64 = _getenv('RDOC_GLOBAL_HOOK_DATA_NAME_64', PRODUCT_NAME + 'GlobalHookData64')
GLOBAL_HOOK_DATA_NAME_32 = _getenv('RDOC_GLOBAL_HOOK_DATA_NAME_32', PRODUCT_NAME + 'GlobalHookData32')
GLOBAL_HOOK_RESTORE_FILENAME = _getenv(
    'RDOC_GLOBAL_HOOK_RESTORE_FILENAME',
    PRODUCT_NAME + '_RestoreGlobalHook.reg',
)

TEMP_SUBFOLDER = _getenv('RDOC_TEMP_SUBFOLDER', PRODUCT_NAME)
APPDATA_SUBFOLDER = _getenv('RDOC_APPDATA_SUBFOLDER', BASE_NAME)
CAPTURE_PROGID = _getenv('RDOC_CAPTURE_PROGID', PRODUCT_NAME + '.RDCCapture.1')
SETTINGS_PROGID = _getenv('RDOC_SETTINGS_PROGID', PRODUCT_NAME + '.RDCSettings.1')

CAPTURE_EXTENSION = _getenv('RDOC_CAPTURE_EXTENSION', '.rdc')
CAPTURE_FILETYPE = _getenv('RDOC_CAPTURE_FILETYPE', 'rdc')
SETTINGS_EXTENSION = _getenv('RDOC_SETTINGS_EXTENSION', '.cap')
SETTINGS_FILETYPE = _getenv('RDOC_SETTINGS_FILETYPE', 'cap')
CAPTURE_MAGIC = _fourcc('RDOC_CAPTURE_MAGIC', 'RIPK')
LEGACY_CAPTURE_MAGIC = _fourcc('RDOC_LEGACY_CAPTURE_MAGIC', 'RDOC')
READ_LEGACY_CAPTURE_MAGIC = _getbool('RDOC_READ_LEGACY_CAPTURE_MAGIC', True)

SECTION_INTERNAL_PREFIX = _getenv('RDOC_SECTION_INTERNAL_PREFIX', BASE_NAME + '/internal/')
SECTION_UI_PREFIX = _getenv('RDOC_SECTION_UI_PREFIX', BASE_NAME + '/ui/')
SECTION_FRAMECAPTURE = _getenv('RDOC_SECTION_FRAMECAPTURE', SECTION_INTERNAL_PREFIX + 'framecapture')
SECTION_RESOLVEDB = _getenv('RDOC_SECTION_RESOLVEDB', SECTION_INTERNAL_PREFIX + 'resolvedb')
SECTION_BOOKMARKS = _getenv('RDOC_SECTION_BOOKMARKS', SECTION_UI_PREFIX + 'bookmarks')
SECTION_NOTES = _getenv('RDOC_SECTION_NOTES', SECTION_UI_PREFIX + 'notes')
SECTION_RESRENAMES = _getenv('RDOC_SECTION_RESRENAMES', SECTION_UI_PREFIX + 'resrenames')
SECTION_EXTHUMB = _getenv('RDOC_SECTION_EXTHUMB', SECTION_INTERNAL_PREFIX + 'exthumb')
SECTION_LOGFILE = _getenv('RDOC_SECTION_LOGFILE', SECTION_INTERNAL_PREFIX + 'logfile')
SECTION_EDITS = _getenv('RDOC_SECTION_EDITS', SECTION_UI_PREFIX + 'edits')
SECTION_D3D12CORE = _getenv('RDOC_SECTION_D3D12CORE', SECTION_INTERNAL_PREFIX + 'd3d12core')
SECTION_D3D12SDKLAYERS = _getenv('RDOC_SECTION_D3D12SDKLAYERS', SECTION_INTERNAL_PREFIX + 'd3d12sdklayers')
SECTION_EMBEDDED_EXTERNALS = _getenv(
    'RDOC_SECTION_EMBEDDED_EXTERNALS',
    SECTION_INTERNAL_PREFIX + 'embeddedexternalfiles',
)

CRASH_EVENT_NAME = _getenv('RDOC_CRASH_EVENT_NAME', BASE_NAME_UPPER + '_CRASHHANDLE')
BREAKPAD_PIPE_PREFIX = _getenv('RDOC_BREAKPAD_PIPE_PREFIX', PRODUCT_NAME + 'BreakpadServer')
UPDATE_TEMPDIR = _getenv('RDOC_UPDATE_TEMPDIR', PRODUCT_NAME + 'Update')

WEBSITE_URL = _getenv('RDOC_WEBSITE_URL', 'https://renderdoc.org')
DOCUMENTATION_TITLE = _getenv('RDOC_DOCUMENTATION_TITLE', PRODUCT_NAME + ' Documentation')
DOCUMENTATION_HTML_TITLE = _getenv('RDOC_DOCUMENTATION_HTML_TITLE', PRODUCT_NAME + ' documentation')
DOCUMENTATION_COLLECTION_NAME = _getenv('RDOC_DOCUMENTATION_COLLECTION_NAME', PRODUCT_NAME)
DOCUMENTATION_BASENAME = _getenv('RDOC_DOCUMENTATION_BASENAME', BASE_NAME)
DOCUMENTATION_FILE = _getenv('RDOC_DOCUMENTATION_FILE', DOCUMENTATION_BASENAME + '.chm')
DOCUMENTATION_URL = _getenv('RDOC_DOCUMENTATION_URL', WEBSITE_URL + '/docs')
PYTHON_API_URL = _getenv('RDOC_PYTHON_API_URL', DOCUMENTATION_URL + '/python_api/index.html')
IN_APPLICATION_API_URL = _getenv('RDOC_IN_APPLICATION_API_URL', DOCUMENTATION_URL + '/in_application_api.html')
BUILDS_URL = _getenv('RDOC_BUILDS_URL', WEBSITE_URL + '/builds')
UPDATE_URL_PATTERN = _getenv(
    'RDOC_UPDATE_URL_PATTERN',
    WEBSITE_URL + '/getupdateurl/{bitness}/{version}?htmlnotes=1',
)
TIPS_URL_PATTERN = _getenv('RDOC_TIPS_URL_PATTERN', WEBSITE_URL + '/tips/{index}')
SUPPORT_EMAIL = _getenv('RDOC_SUPPORT_EMAIL', 'baldurk@baldurk.org')
SOURCE_REPO_USER = _getenv('RDOC_SOURCE_REPO_USER', 'baldurk')
SOURCE_REPO_NAME = _getenv('RDOC_SOURCE_REPO_NAME', 'renderdoc')
SOURCE_URL = _getenv('RDOC_SOURCE_URL', f'https://github.com/{SOURCE_REPO_USER}/{SOURCE_REPO_NAME}')
ISSUES_URL = _getenv('RDOC_ISSUES_URL', SOURCE_URL + '/issues')
CONTRIB_URL = _getenv('RDOC_CONTRIB_URL', 'https://github.com/baldurk/renderdoc-contrib')
BUGREPORT_URL = _getenv('RDOC_BUGREPORT_URL', WEBSITE_URL + '/bugreporter')
ANALYTICS_URL = _getenv('RDOC_ANALYTICS_URL', WEBSITE_URL + '/analytics')
SUPPORT_BUG_URL = _getenv('RDOC_SUPPORT_BUG_URL', _mailto_url(f'{PRODUCT_NAME} bug'))
SUPPORT_FEEDBACK_URL = _getenv('RDOC_SUPPORT_FEEDBACK_URL', _mailto_url(f'{PRODUCT_NAME} feedback'))
SUPPORT_QUESTION_URL = _getenv('RDOC_SUPPORT_QUESTION_URL', _mailto_url(f'{PRODUCT_NAME} question'))
SUPPORT_UNRECOVERABLE_URL = _getenv(
    'RDOC_SUPPORT_UNRECOVERABLE_URL',
    _mailto_url(f'{PRODUCT_NAME} Unrecoverable error'),
)

PY_CORE_MODULE_NAME = _getenv('RDOC_PY_CORE_MODULE_NAME', BASE_NAME)
PY_GUI_MODULE_NAME = _getenv('RDOC_PY_GUI_MODULE_NAME', UI_NAME)
KEEP_LEGACY_PYTHON_ALIASES = _getbool('RDOC_KEEP_LEGACY_PYTHON_ALIASES', False)
KEEP_LEGACY_ABI = _getbool('RDOC_KEEP_LEGACY_ABI', True)
KEEP_LEGACY_POSIX_ENVS = _getbool('RDOC_KEEP_LEGACY_POSIX_ENVS', False)

LINUX_CORE_LIBRARY = _getenv('RDOC_LINUX_CORE_LIBRARY', 'lib' + BASE_NAME + '.so')
APPLE_CORE_LIBRARY = _getenv('RDOC_APPLE_CORE_LIBRARY', 'lib' + BASE_NAME + '.dylib')
ANDROID_CAPTURE_LIBRARY = _getenv('RDOC_ANDROID_CAPTURE_LIBRARY', 'lib' + ANDROID_OUTPUT_NAME + '.so')

VULKAN_LAYER_NAME = _getenv('RDOC_VULKAN_LAYER_NAME', 'VK_LAYER_' + BASE_NAME_UPPER + '_Capture')
VULKAN_CAPTURE_VAR = _getenv('RDOC_VULKAN_CAPTURE_VAR', 'ENABLE_VULKAN_' + BASE_NAME_UPPER + '_CAPTURE')
VULKAN_LAYER_DESCRIPTION = _getenv('RDOC_VULKAN_LAYER_DESCRIPTION', 'Debugging capture layer for ' + PRODUCT_NAME)
VULKAN_FORCED_INSTANCE_NAME = _getenv('RDOC_VULKAN_FORCED_INSTANCE_NAME', PRODUCT_NAME + ' forced instance')
VULKAN_TOOL_NAME = _getenv('RDOC_VULKAN_TOOL_NAME', PRODUCT_NAME)
VULKAN_TOOL_DESCRIPTION = _getenv('RDOC_VULKAN_TOOL_DESCRIPTION', VULKAN_LAYER_DESCRIPTION)
VULKAN_CAPTURE_APP_NAME = _getenv('RDOC_VULKAN_CAPTURE_APP_NAME', PRODUCT_NAME + ' Capturing App')
VULKAN_ENGINE_NAME = _getenv('RDOC_VULKAN_ENGINE_NAME', PRODUCT_NAME)

ANDROID_LIBRARY = _getenv('RDOC_ANDROID_LIBRARY', 'libVkLayer_GLES_' + PRODUCT_NAME + '.so')
CMD_ANDROID_PACKAGE_BASE = _getenv('RDOC_CMD_ANDROID_PACKAGE_BASE', 'org.' + BASE_NAME + '.' + CMD_NAME)
CMD_ANDROID_EXTRA_KEY = _getenv('RDOC_CMD_ANDROID_EXTRA_KEY', CMD_NAME)
TEST_ANDROID_DEMO_PACKAGE_BASE = _getenv('RDOC_TEST_ANDROID_DEMO_PACKAGE_BASE', BASE_NAME + '.org.demos')
ANDROID_ACTIVITY_LABEL = _getenv('RDOC_ANDROID_ACTIVITY_LABEL', PRODUCT_NAME)
ANDROID_APPLICATION_LABEL = _getenv('RDOC_ANDROID_APPLICATION_LABEL', CMD_DISPLAY_NAME)
ANDROID_APK_BASENAME = _getenv('RDOC_ANDROID_APK_BASENAME', CMD_DISPLAY_NAME)
ANDROID_PROPERTY_PREFIX = _getenv('RDOC_ANDROID_PROPERTY_PREFIX', 'debug.' + BASE_NAME)
ANDROID_AUTOGRANT_PERMISSIONS_PROPERTY = _getenv(
    'RDOC_ANDROID_AUTOGRANT_PERMISSIONS_PROPERTY',
    ANDROID_PROPERTY_PREFIX + '.autograntpermissions',
)
ANDROID_IGNORE_LAYERS_PROPERTY = _getenv(
    'RDOC_ANDROID_IGNORE_LAYERS_PROPERTY',
    ANDROID_PROPERTY_PREFIX + '.IGNORE_LAYERS',
)
ANDROID_SOCKET_PREFIX = _getenv('RDOC_ANDROID_SOCKET_PREFIX', BASE_NAME)

ENV_NAMESPACE = _getenv('RDOC_ENV_NAMESPACE', BASE_NAME_UPPER)
ENV_ORIGLIBPATH = _getenv('RDOC_ENV_ORIGLIBPATH', ENV_NAMESPACE + '_ORIGLIBPATH')
ENV_ORIGPRELOAD = _getenv('RDOC_ENV_ORIGPRELOAD', ENV_NAMESPACE + '_ORIGPRELOAD')
ENV_CAPFILE = _getenv('RDOC_ENV_CAPFILE', ENV_NAMESPACE + '_CAPFILE')
ENV_CAPOPTS = _getenv('RDOC_ENV_CAPOPTS', ENV_NAMESPACE + '_CAPOPTS')
ENV_DEBUG_LOG_FILE = _getenv('RDOC_ENV_DEBUG_LOG_FILE', ENV_NAMESPACE + '_DEBUG_LOG_FILE')
ENV_TEMP = _getenv('RDOC_ENV_TEMP', ENV_NAMESPACE + '_TEMP')
ENV_HOOK_EGL = _getenv('RDOC_ENV_HOOK_EGL', ENV_NAMESPACE + '_HOOK_EGL')
ENV_DEMOS_DATA = _getenv('RDOC_ENV_DEMOS_DATA', ENV_NAMESPACE + '_DEMOS_DATA')
ANDROID_CAPTURE_OPTIONS_PROPERTY = _getenv(
    'RDOC_ANDROID_CAPTURE_OPTIONS_PROPERTY',
    ANDROID_PROPERTY_PREFIX + '.' + ENV_CAPOPTS,
)

POSIX_CONFIG_DIR = _getenv('RDOC_POSIX_CONFIG_DIR', '.' + BASE_NAME)
POSIX_SHARE_DIR = _getenv('RDOC_POSIX_SHARE_DIR', BASE_NAME)
SETTINGS_FILENAME = _getenv('RDOC_SETTINGS_FILENAME', BASE_NAME + '.conf')
REMOTE_SERVER_CONFIG_FILENAME = _getenv('RDOC_REMOTE_SERVER_CONFIG_FILENAME', 'remoteserver.conf')
PLUGINS_SHARE_SUBDIR = _getenv('RDOC_PLUGINS_SHARE_SUBDIR', 'share/' + POSIX_SHARE_DIR + '/plugins')
ANDROID_PLUGINS_SHARE_SUBDIR = _getenv(
    'RDOC_ANDROID_PLUGINS_SHARE_SUBDIR',
    PLUGINS_SHARE_SUBDIR + '/android',
)
PYLIBS_SHARE_SUBDIR = _getenv('RDOC_PYLIBS_SHARE_SUBDIR', 'share/' + POSIX_SHARE_DIR + '/pylibs')

MIME_TYPE = _getenv('RDOC_MIME_TYPE', 'application/x-' + BASE_NAME + '-capture')
MIME_ICON_NAME = _getenv('RDOC_MIME_ICON_NAME', 'application-x-' + BASE_NAME + '-capture')
DESKTOP_FILENAME = _getenv('RDOC_DESKTOP_FILENAME', BASE_NAME + '.desktop')
THUMBNAILER_FILENAME = _getenv('RDOC_THUMBNAILER_FILENAME', BASE_NAME + '.thumbnailer')
CAPTURE_XML_FILENAME = _getenv('RDOC_CAPTURE_XML_FILENAME', BASE_NAME + '-capture.xml')
MENU_FILENAME = _getenv('RDOC_MENU_FILENAME', BASE_NAME)
PIXMAP_ICON_16_FILENAME = _getenv('RDOC_PIXMAP_ICON_16_FILENAME', BASE_NAME + '-icon-16x16.xpm')
PIXMAP_ICON_32_FILENAME = _getenv('RDOC_PIXMAP_ICON_32_FILENAME', BASE_NAME + '-icon-32x32.xpm')
THUMBNAIL_HANDLER_NAME = _getenv('RDOC_THUMBNAIL_HANDLER_NAME', PRODUCT_NAME + ' Thumbnail Handler')
FILE_ASSOCIATIONS_DESCRIPTION = _getenv(
    'RDOC_FILE_ASSOCIATIONS_DESCRIPTION',
    f'Associate {CAPTURE_EXTENSION} (Capture logs) and {SETTINGS_EXTENSION} (Capture settings) files with {PRODUCT_NAME}.',
)
